name: npm 라이브러리 배포

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Check package version and update if needed
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          LATEST_VERSION=$(npm view ${{ github.event.repository.name }} version || echo "0.0.0")
          
          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            # package.json 버전이 변경되지 않았다면 패치 버전을 증가
            npm version patch
          else
            echo "Using version from package.json: $CURRENT_VERSION"
          fi
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
